.editorconfig
.github/workflows/cargo-build-and-test.yml
.github/workflows/check-links.yml
.github/workflows/pre-commit.yml
.markdownlint.yaml
.pre-commit-config.yaml
.vscode/extensions.json
.vscode/settings.json
CODE_OF_CONDUCT.md
README.md

I took the hooks we use in our Poetry template as a starting point, removed the Python-specific ones and added a formatter for Rust.
I initially tried to set up this repo with [pre-commit.ci](https://pre-commit.ci), but unfortunately the Rust formatter requires the `rustfmt` tool to be installed and there doesn't appear to be a way to install extra arbitrary software into the pre-commit.ci containers. They do, however, provide a GitHub Action which automatically applies fixes from `pre-commit`, so we can replicate the functionality that way.
Closes #4.

Add `pre-commit` hooks

---

.pre-commit-config.yaml

Clippy is a static analyser to catch common stylistic problems. It is bundled with Rust's default tools. More information is available here: https://doc.rust-lang.org/stable/clippy/index.html
This PR adds a `pre-commit` hook for automatically checking code with clippy. I was in two minds about whether a running a static analyser with every commit might make things irritatingly slow, but the code base is tiny for now, so the overhead is minimal, and if it does ever become a pain, we can always disable it and just run clippy as a GitHub Action instead. For Rust learners (like me) it probably is quite helpful to have these stylistic issues flagged up interactively anyway.
Closes #22.

Add clippy to pre-commit hooks

---

.github/workflows/cargo-build-and-test.yml

The macOS runner is currently failing, for reasons unknown (#43).
It seems to be something to do with the `highs` crate and I've raised an issue upstream, but for now, let's just disable the macOS runner so it isn't a blocker.

CI: Temporarily disable macOS runner

---

.github/workflows/docs.yml
README.md
src/muse2/settings.rs

For now, I'm just publishing the API docs to GitHub Pages. We do also want to publish a manual (#36) but I'll do this in a separate PR.
I temporarily bypassed the environment protection rules to deploy from this branch so I could check that it worked. The result is here: https://energysystemsmodellinglab.github.io/MUSE_2.0/muse2/index.html
Closes #15.

Add workflow to deploy API docs to GitHub Pages

---

.github/workflows/cargo-build-and-test.yml

This PR enables caching for cargo artifacts on GitHub Actions, which should drastically speed things up (currently we're building some very big libraries from source every time the CI runs).
Commit summary:
- **CI: Use better names for actions**
- **CI: Also make warnings fatal for Ubuntu runner**
- **CI: Also test-build application on Ubuntu runner**
- **CI: Enable caching of cargo artifacts**
Closes #41.
Tagging @cc-a in case you're interested!

CI tweaks and add caching for cargo

---

examples/simple/time_slices.csv

Currently it is assumed that the number of times of day will be the same for every season, but according to @ahawkes we may want more flexibility.
Accordingly, I've updated `time_slices.csv` to have three columns: season, time of day and value.
Fixes #65.
I used the following Python script to generate this file from the original settings.toml file:
```py
import pandas as pd
import tomllib
def main(file_path):
print(f"loading {file_path}")
with open(file_path, "rb") as f:
data = tomllib.load(f)
time_slices = data["time_slices"]
rows_list = []
for season, tod_dict in time_slices.items():
for tod, value in tod_dict.items():
rows_list.append([season, tod, value])
df = pd.DataFrame(rows_list, columns=["Season", "Time of Day", "Value"])
df.to_csv("time_slices.csv", index=False)
if __name__ == …
```

`time_slices.csv`: Put time of day in separate column

---

.github/workflows/cargo-build-and-test.yml

I've noticed that @Ashmit8583 is using macOS, so given that we have at least one mac user, we probably need to be testing this platform too.
As this code isn't using the `highs` crate anymore, there won't be build failures (see https://github.com/EnergySystemsModellingLab/MUSE_2.0/issues/43). That said, it also seems like the HiGHS example code is also working with macOS again (I've opened a PR: https://github.com/EnergySystemsModellingLab/highs-example-rust/pull/3)!
I'm still unsure of what the problem was (no one has replied to me in the upstream repo: https://github.com/rust-or/highs/issues/17), but at least it's working now.

Re-enable testing on macOS

---

Cargo.toml

This PR adds some additional metadata to `Cargo.toml`. This information is used to describe Rust packages on https://crates.io/ where we will probably want to publish MUSE 2.0 at some point.
Some of the information was lifted from MUSE v1's manifest.
@ahawkes Would you mind checking that you're happy with the description etc.?
Closes #9.

Add metadata to Cargo.toml

---

.vscode/launch.json

In order for debug to work, the debug config file (Launch.json) needs to point at the right directory. This change fixes that.
Fixes # 86

updating the path in launch.json

---

.pre-commit-config.yaml

Reported by @ahawkes.
Currently an error message is displayed if the formatting is not correct, but files are not automatically reformated. Let's fix that.
The reason I didn't notice sooner is because we have the VS Code settings for this project set to autoformat Rust files on save, but we shouldn't rely on this!

pre-commit: Automatically reformat Rust files

---

src/settings.rs
src/simulation.rs

I'm currently merging the changes from #80 into my PR and I think the error-handling could be a bit tidier. No offence @Ashmit8583! This is exactly how I did things in my example code, but I've learned a bit more about error handling in Rust since then. While errors due to reading settings files should result in a panic, I think it's cleaner to pass the errors back up the callstack a bit and let the errors be dealt with in a common place in `simulation::run()`. That way we can print `"Something went wrong while loading settings: {thing that went wrong}"` rather than having `panic!`s dotted about the input reading code.
I also renamed a couple of variables for consistency.
@Ashmit8583 I've tagged you as a reviewer because this is your code so it would be good if you could take a look.

Tidy settings error handling

---

src/input.rs
src/main.rs
src/time_slices.rs

Following @dalonsoa's suggestion in #94, I've had a go at a generic `read_vec_from_csv` function, which should reduce the amount of boilerplate code for other CSV readers.
While I was at it, I thought I'd see how things looked if I used the `nonempty-collections` crate to statically enforce the non-emptiness of some containers -- I've written a `read_nevec_from_csv` function to use this and I've used it for the time slices code.
I'm happy-ish with how things look, but using `NESlice`s instead of native Rust slices has introduced a bit of ugliness in the tests. Maybe it's ok there though.
Thoughts and suggestions welcome!
Closes #94. Closes #96.

Generic CSV reader and non-empty collections

---

examples/simple/agent_objectives.csv
examples/simple/agent_regions.csv
examples/simple/agents.csv
examples/simple/assets.csv
examples/simple/commodities.csv
examples/simple/commodity_constraints.csv
examples/simple/commodity_costs.csv
examples/simple/demand.csv
examples/simple/demand_slicing.csv
examples/simple/process_availabilities.csv
examples/simple/process_flow_share_constraints.csv
examples/simple/process_flows.csv
examples/simple/process_investment_constraints.csv
examples/simple/process_pacs.csv
examples/simple/process_parameters.csv
examples/simple/process_regions.csv
examples/simple/processes.csv
examples/simple/regions.csv

There are many places in the CSV files where rows in one file are referred to in another, e.g. commodities defined in commodities.csv are referred to via a "commodity_name" column elsewhere. Agents and regions are the exception: they're referred to with "agent" and "region", respectively.
As "name" is a little ambiguous, I've used an "id" suffix instead. In files that provide a list of these IDs (e.g. agents.csv) the column is just "id" now, which is terser and more in keeping with what databases do.
I've changed the "constraint_name" column to "commodity_constraint_id" because I think that's clearer.
Closes #101.

Rename columns in CSV files to use "_id" suffix

---

Cargo.toml
examples/simple/settings.toml
src/log.rs
src/main.rs
src/settings.rs
src/simulation.rs

For various reasons, it's better to use a proper logging library rather than having print statements dotted throughout the code.
I've added `env_logger` as a dependency (it seems to be a conservative choice) and used it in a few places in the code. The default output will look something like this:
```
[2024-07-02T15:21:11Z INFO  muse2::simulation] Loading settings from "examples/simple/settings.toml"
```
We can always configure it later if we want it to look different.
Closes #91.

Add program logger

---

src/demand.rs
src/input.rs
src/settings.rs
src/time_slices.rs

While working on #64, it's become apparant to me that the error messages we're outputting are not as informative as they could be. Specifically, we don't indicate to the user which input files the errors relate to, which makes tracking down problems rather difficult.
In this PR, I've introduced a error type, `InputError`, which takes a file path as well as a message as an argument, so that we can notify users about this. I've updated all the input-related functions to use this as an error type.
Unrelated: I also renamed a few things in `demand.rs` for consistency.

Make input-file errors more informative

---

src/demand.rs
src/input.rs
src/time_slices.rs

Currently, both the `read_time_slices()` and `read_demand_data()` functions return an error if there are no entries in the CSV files. Instead of doing this for every CSV reader, we can just implement this check in the generic `read_vec_from_csv()` function, which is what I've done here.
This of course makes it a general policy across all CSV files (though we could gate the check with an argument, if we wanted). I'm just wondering if we want this policy? For time slices, we disallow empty CSV files, but users can omit the `time_slices_path` option in `settings.toml` to get the default value (albeit we issue a warning). I guess for other files that are optional we want to do something similar, i.e. disallow empty CSV files but let users omit the relevant option in `settings.toml`.
Thoughts? …

Disallow empty CSV files

---

Cargo.toml
examples/simple/commodities.csv
examples/simple/commodity_constraints.csv
examples/simple/commodity_costs.csv
examples/simple/demand_slicing.csv
examples/simple/process_availabilities.csv
examples/simple/process_flow_share_constraints.csv
examples/simple/processes.csv
examples/simple/settings.toml
src/input.rs
src/main.rs
src/process.rs
src/settings.rs
src/simulation.rs
src/time_slices.rs

This is a rough draft of code to read in most of the process-related CSV files. I generated the data structures with a Python script to guess the column types, then edited the results. Most of my effort was spent on integrating the data structures together, which isn't something we've done elsewhere in the codebase so far. The result is that we have a `read_processes()` function, which returns a `Vec<Process>`. Each `Process` struct also contains vectors representing its associated availabilities, flows, PACs, parameters and regions. I omitted code for reading the flow share and investment constraints files following @ahawkes' suggestion (the example files are currently also empty), but I'll open separate issues to solve these.
I also noticed that the first column in `processes.csv` is …

Add support for reading (most) process-related CSV files

---

CONTRIBUTING.md
docs/SUMMARY.md
docs/chapter_1.md
docs/introduction.md
docs/user_guide.md
mlc_config.json

As suggested by @ahawkes, this PR documents how to configure the program logger. I've put it in `CONTRIBUTING.md` for now. At some point, we should probably move developer/user documentation to the `docs` folder so it will appear on our GitHub Pages, but that's a job for another day.
Note that there isn't currently a way to tell MUSE itself to write the log to a file (see discussion in #110).
Closes #111.

Document how to use the logging library

---

src/input.rs
src/process.rs

This PR adds the missing unit tests to `input.rs` and `process.rs`. In `process.rs`, I haven't written a test for the high-level `read_processes` function as it is complicated and already covered by the integration test.
I thought I should finish up the tests before adding new features.
Fixes #115. Fixes #116.

Add missing unit tests for input code

---

.github/workflows/cargo-build-and-test.yml
.github/workflows/docs.yml
examples/simple/model.toml
examples/simple/settings.toml
src/demand.rs
src/input.rs
src/lib.rs
src/log.rs
src/main.rs
src/model.rs
src/process.rs
src/region.rs
src/settings.rs
src/simulation.rs
src/time_slice.rs
tests/model.rs

We want to keep the program and model configuration separate, because:
- It will the config files clearer for end users
- It makes it easier to have a proper separation of concerns in the code
- It makes it easier to share models (without having to remove user-specific preferences from your colleagues' files)
I've split up the old `settings.toml` into `settings.toml` (for program settings) and `model.toml` (for model parameters), which are processed by separate corresponding Rust modules (`settings.rs` and `model.rs`). While I was refactoring, I did some misc tidying, including adding a validity check for the milestone years (#113) and moving the one integration test we have to the a separate `tests` folder, which is apparantly best practice. In order to do the latter, I had to add a …

Separate model and program settings

---

.github/CODEOWNERS

Given that @tsmbland will be reviewing things while @dalonsoa is away, let's just add him to the `CODEOWNERS` file now.
If/when @dalonsoa and I stop being involved in PR reviews, we can take ourselves out of the file.
Everyone happy with this?

Add Tom to `CODEOWNERS`

---

src/demand.rs
src/input.rs
src/main.rs
src/model.rs
src/process.rs
src/region.rs
src/settings.rs
src/time_slice.rs
tests/model.rs

Currently we handle input errors by returning `InputResult`s from basically all input-related functions and passing this result up the callstack, ultimately to `main()`. If there is an error, the program terminates.
Given that we never actually use these returned error values, all this means is the code has to jump through a bunch of hoops to convert all possible errors to our custom `InputError` type, which makes it unnecessarily complicated.
The alternative is to `panic!` when you encounter errors, which is the way you're supposed to deal with unrecoverable errors: https://doc.rust-lang.org/book/ch09-00-error-handling.html
I've converted the existing code to panic in case of error (via some helpers). This does mean that there's a fair amount of churn in this PR, but it will make the …

Simplify input error handling

---

src/model.rs
src/process.rs
src/region.rs

This PR adds validation for the regions associated with processes. I've written the code in a generic way so that it can be reused (in particular for reading in commodities). It allows for entering `"all"` as a region ID, which means that the process is active in every region. There is thorough error checking and I've written lots of tests for this -- so while the diff looks rather large, it is mostly because of these tests! I also added some tests that were missing for `process.rs`.
Closes #138. Closes #141.

Validate region IDs for processes

---

src/input.rs
src/lib.rs
src/model.rs
src/process.rs
src/time_slice.rs

This PR adds code to validate the time slices as they are loaded and provides some new types (`TimeSliceID`, `TimeSliceSelection`) to work with time slices safely. It adds time slice validation to the process-related code.
Following feedback for #146, I've changed things so we don't read the time slices from `model.toml`. Instead, they are just extracted from `time_slices.csv`, as before.
Closes #109.

Add validation for time slices (without sorting)

---

examples/simple/agent_objectives.csv
src/agent.rs
src/lib.rs
src/model.rs
src/region.rs

This PR adds support for reading in the various agent-related CSV files, viz.: `agents.csv`, `agent_regions.csv` and `agent_objectives.csv`.
Closes #76. Closes #107. Closes #108.

Read in agents-related files

---

src/commodity.rs
src/lib.rs
src/model.rs
src/process.rs
src/time_slice.rs

The latest installment of the input layer work. This one is minimally invasive; it just adds support for two commodity-related CSV files (`commodities.csv` and `commodity_costs.csv`).
The commodity constraints file (which is currently empty in the example) is not read in by this code, but I've opened an issue to tackle it in future: #149.
Closes #62.

Read in commodities-related CSV files

---

src/process.rs

Adds more validation to the process parameters. In addition to what's described in #163, if also validates the lifetime since, presumably, it should be a number greater than zero, and not just positive.
Fixes #163

More validation

---

examples/simple/process_pacs.csv
src/commodity.rs
src/model.rs
src/process.rs

Now that we have merged the commodity-related code, we can use these data structures elsewhere.
As PACs are commodities, it makes sense to represent them as references to commodity types, which is what I've done here. There are currently no tests, but we can add these later.
Edit: PACs are "Primary Activity Commodities": From the glossary:
> "**Primary Activity Commodity (PAC):** The PACs specify which output/s are linked to the process
capacity. The combined output of all PACs cannot exceed the *Asset’s* capacity. A user can define
which output/s are PACs."
Closes #164.

Make PACs references to `Commodity`s

---

CONTRIBUTING.md
book.toml
docs/SUMMARY.md
docs/developer_guide.md
docs/dispatch_optimisation.md
docs/introduction.md

I thought it made sense to have this in a place where it's easily accessible. We can revise it as we go along. I used `pandoc` to auto-convert it from the SRS, but the equations in particular required a lot of manual tweaking to work (among other things it seems like in some contexts you have to escape the underscore in LaTeX equations, even where it's being used for a subscript). The content should be exactly the same as in the SRS though and I've double-checked that the equations all look ok.
To test it locally:
1. Install mdbook: `cargo install mdbook`
2. Serve: `mdbook serve -o`
I'm also happy to send screenshots if anyone doesn't want to go through this rigmarole.
@ahawkes Are you happy with this?
Closes #161.

Add draft dispatch formulation to docs

---

.github/workflows/cargo-build-and-test.yml
.github/workflows/check-links.yml
.github/workflows/docs.yml
.github/workflows/pre-commit.yml

This PR uses a new and improved Rust setup action for CI workflows, as suggested by @cc-a. It seems to be better maintained and handles the cargo caching business itself, which means we can simplify our workflows a bit.
It also gave me a chance to revisit all the hackery we were doing to make `cargo tarpaulin` work (which we use to generate code coverage). Previously, you needed a nightly build of cargo etc. to make it work, but that no longer appears to be necessary so now it's just a case of running `cargo install cargo-tarpaulin`.
Closes #133. Closes #49.

Use new Rust action for CI

---

src/commodity.rs
src/demand.rs
src/input.rs
src/lib.rs
src/model.rs

This PR adds support for reading in `demand_slicing.csv`, which determines how demand varies with time slice.
While I was at it, I reworked the data structures we use for storing demand data such that:
1. Demand is now a field of commodities
2. Demand is grouped by region ID
In retrospect, I might have been a bit premature in implementing the second one: it only really makes sense if we will be looking at demand region by region for each commodity, which I *think* is the case, though I'm not totally sure. I thought I should just ask for advice on this though rather than just unpicking it from the other work. Thoughts welcome!
Closes #61.

Read in demand slices

---

src/process.rs

Use the `anyhow` crate's features in `process.rs`, including `Result`, `ensure!` etc. This simplifies the error handling and also fixes a `clippy` warning (see #207).
Closes #200.

Use `anyhow` crate for `process.rs`

---

src/time_slice.rs

I was going to refactor `time_slice.rs` a bit for #202 anyway, so I thought it made sense to convert it over to using `anyhow` first.
Closes #201.

Use `anyhow` crate for `time_slice.rs`

---

.github/CODEOWNERS

We don't really need to be tagging everyone on every PR, so let's remove this file.
I've updated the branch protection rule so that reviews from code owners are no longer required.
Closes #214.

Remove `CODEOWNERS` file

---

src/agent.rs
src/asset.rs
src/lib.rs
src/model.rs
src/process.rs

This PR adds the code for reading in assets from the `assets.csv` file along with providing the relevant data structures. These assets are assigned to a field of the corresponding `Agent`. I've used the `anyhow` crate for the error handling.
I've got a question for anyone who has an idea: currently the code allows for agents that have no assets, but does that make sense? It sounds a bit daft to me, but then again I may be misunderstanding what it is that agents are supposed to do.
FYI @Sahil590 I've used the definitions in the SRS for the doc comments, so that's another bit of #162 done.
Closes #63.

Add code to read in assets

---

src/demand.rs

This PR changes `demand.rs` to use `anyhow`, which should make it tidier.
While I was at it, I fixed a couple of other things:
- `DemandSliceRaw` was public, even though it didn't need to be
- I added missing doc comments to all the public bits of code
Closes #205. Closes #217.

Use `anyhow` for `demand.rs` + misc tidying

---

.github/workflows/cargo-build-and-test.yml
docs/developer_guide.md

Currently we're using [tarpaulin](https://github.com/xd009642/tarpaulin) to generate test coverage. The only problem is that it produces a lot of false negatives (i.e. falsely reports that some lines of code aren't covered by tests), which limits its utility.
After looking around it seems that tarpaulin's approach to calculating code coverage is actually rather outdated and nowadays you can leverage Rust's compiler backend (LLVM) to generate better, source-based coverage. Cargo-llvm-cov is just a fairly thin wrapper around `rustc`'s built-in functionality.
The coverage stats look much better with cargo-llvm-cov: it covers about 14% more code :partying_face:.
Closes #228.

Replace use of tarpaulin with cargo-llvm-cov for test coverage

---

src/demand.rs

Some of the types used in `demand.rs` are quite complex. `clippy` warns about this and suggests using type aliases for readability, which is what I've done.
I was going to include this in a larger PR with some more demand-related changes, but given that this bug is now breaking the CI (see #238), I thought it better to make this small PR now so that we can get it reviewed and merged sooner.
Fixes #207.

Make a `DemandHashMap` type alias

---

src/commodity.rs
src/input.rs
src/model.rs
src/process.rs
src/region.rs

This PR Goes part of the way towards replacing the `unwrap_input_err` method with `with_context` from anyhow. This is partly addressing both #191 and #232. It does this by creating a function `input_err_msg` that is for ease of use whenever using `with_context` to add context to an error. It also removes all individual uses of the `input_panic` function.
Outstanding tasks:

Input context messages

---

examples/simple/commodity_costs.csv
src/commodity.rs
src/model.rs
src/process.rs
src/time_slice.rs

Currently commodity costs are specified in a vector belonging to the corresponding commodity. At some point though we will need to actually access these values and this current data structure is a bit limited. Accordingly, I've reorganised the code so that they're specified in a map instead (still assigned to the relevant commodity, though) with a combination of commodity ID, region ID and milestone year used as the key. For the sake of encapsulating this functionality a bit, I've used the [new type idiom](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) to provide a simple wrapper around a `HashMap`, with a `get` method for accessing its contents.
This is in some ways similar to the refactor I want to do for demand slicing (#231), but unfortunately I've got myself in a …

Refactor commodity costs for easy lookup

---

.vscode/launch.json
Cargo.lock
Cargo.toml
src/main.rs

In this PR I added the clap crate which lets us use the command `muse2` to run models. To get this started, run the following commands 
1. `cargo build`
2. `cargo install --path  .`
now you can run `muse2` and it should show a list of available commands.
For more info about how the clap crate works, I found this [video ](https://www.youtube.com/watch?v=Ot3qCA3Iv_8&t=2583s) very useful. 
Fixes #185  (issue)

adding argument parser using clap

---

src/agent.rs
src/asset.rs
src/commodity.rs
src/demand.rs
src/input.rs
src/model.rs
src/process.rs
src/region.rs
src/time_slice.rs

This PR changes the `read_csv` function in `input.rs` so that it returns a `Result` type to enable propagating errors all the way up to `main`. This required changing all the functions that call `read_csv` and use the outputs of it to also propagate errors. So there are many changes, but they are limited to changing the return types of many functions to `Result` and adding a lot of `?` and `with_context` and `Ok`.
Fixes #249

Make read_csv return a Result type

---

src/input.rs
src/process.rs

Looks like a small change, but the change in `process.rs` was slightly more complicated than I expected. I needed to change away from using the `.map()` to using a `for` loop because the errors couldn't be propagated outside of the closure inside the map. But this required building a `Vec`, which when needed to be converted into an interator to apply `into_id_map`. This feels like it is less efficient than the previous solution, but I can't think of another solution to propagate the errors from `time_slice_info.get_selection`.
Fixes #191
Fixes #157

Remove last use of unwrap_input_err

---

Cargo.lock
Cargo.toml
src/main.rs

This PR changes the way the arg parser works before I was using the builder API approach, but after the comments made in #245 it makes sense to use the derive api so we can use a struct for defining new args in the future. 
Fixes #256  (issue)

Arg parser

---

src/main.rs

This catches and prints errors that are propagated up to main instead of just unwrapping them.
I've included a test to check the right `context` is included in the error. It's a bit convoluted, but I couldn't find a better way. Any suggestions are welcome there.
Also, there are some more uses of `unwrap` throughout the code which should be changed, so I don't think the can mark #232 as complete until an audit of those have been done.
Fixes #233

Print errors instead of unwrapping in main

---

Cargo.lock
Cargo.toml
src/main.rs

@alexdewar is this what you had in mind with the include_dir crate? Still having some trouble with the `muse2 example simple` command, but this is a good starting point to get a list of examples.
Currently, this PR only implements the `muse2 example list` command, which retrieves the list of folders in the examples' directory. 
Fixes #271  (issue)

initial attempt at adding the example arg and adding include_dir crate

---

.vscode/launch.json

The debug config option for tests currently doesn't work. For some reason, when I run it, it just runs the one test. Changing it to run `cargo test` seems to fix things, so we can now debug tests and set breakpoints in them etc.
Note that this can only be launched from the "run and debug" panel; we still don't have proper integrated test support in VS Code for Rust :disappointed:

VS Code: Fix debug config for tests

---

src/process.rs

This adds a check in `read_process_pacs_from_iter` to make sure the PACs for each process are either all inputs or all outputs.
I do this by looping through the processes and creating a flag `current_flow_sign` which is compared against the commodity flow for each PAC (positive flows represent outputs, negative flows represent inputs). Implicit is the assumption that flows cannot be zero - I don't think we actually have this check anywhere, we we should add this in.
This required passing `flows` to this function and also `read_process_pacs`. I had to modify all the tests accordingly, and have added a new test.
Fixes #165

Check that all PACs are inputs or outputs

---

docs/dispatch_optimisation.md
src/input/process.rs
src/input/process/availability.rs
src/input/process/flow.rs
src/input/process/parameter.rs

I've added some extra validation steps related to process flows, namely:
* Check that process flows are valid numbers
* Check that flow costs are valid numbers
* Check that every process has at least one associated process flow (i.e. it produces or consumes *something*)
* Disallow commodity flexible flows for now (we will only support fixed ones for now)
I also added a check that every process has at least one PAC.
Closes #277. Closes #278. Closes #279.

Add some more validation checks for process flows

---

src/agent.rs
src/input/agent.rs
src/input/agent/objective.rs
src/model.rs

This PR changes the CSV-reading code for agents so that we can use an `Rc<Commodity>` for the relevant field rather than an unvalidated commodity ID, which is what we have now. I've refactored things so the input code is more like what we've done for other structs: there's now an `AgentRaw` struct with the raw info in, which is then further processed into a "proper" `Agent` struct. This also means I was able to tidy the code for parsing the agents' search space (which is composed of process IDs). Finally, I added missing doc comments and enabled doc warnings for `src/agent.rs` (#215).
Closes #215. Closes #319.

Validate agent commodity IDs + other tidy-ups

---

src/agent.rs
src/commands.rs
src/input/agent/asset.rs
src/lib.rs
src/log.rs
src/model.rs
src/simulation.rs

Since work has begun on MUSE 2.0, the program has just printed the contents of the loaded model using default implementations of the `Debug` trait. Now that we're reading in almost all of the input files, the model's data structures are rather convoluted so the output is also very convoluted and completely unreadable. This PR changes the code to print something more human readable instead, iterating over data structures in roughly the way we will need to do for the actual simulation. I've added various helper methods for this.
The motivation for this change is that I wanted to work on a draft of the dispatch optimisation code (mostly just to clarify how it worked in my own head) and found that it made sense to write these various helpers, so I thought they should be merged by themselves …

A prettier placeholder `run()` function + some helper functions

---

src/input/agent.rs
src/input/agent/objective.rs
src/input/process/flow.rs

Seems I should have been a bit more careful about merging all those PRs at once... Now the tests are failing to compile (see below for output).
I guess this is the downside of unchecking the "require branches to be up to date" option.
Errors:
```
Compiling muse2 v2.0.0-dev1 (/home/alex/code/MUSE_2.0)
error[E0560]: struct `commodity::Commodity` has no field named `demand_by_region`
--> src/input/agent/objective.rs:165:13
|
165 |             demand_by_region: HashMap::new(),
|             ^^^^^^^^^^^^^^^^ `commodity::Commodity` does not have this field
|
= note: available fields are: `demand`
error[E0560]: struct `commodity::Commodity` has no field named `demand_by_region`
--> src/input/agent.rs:173:13
|
173 |             demand_by_region: HashMap::new(),
|             ^^^^^^^^^^^^^^^^ …
```

Fix: Change of demand field causing compile failures

---

src/input.rs
src/input/time_slice.rs
src/model.rs
src/time_slice.rs

This PR moves the time slice CSV code to a submodule of `input`, as we've done for all the other modules now. This is the last bit of refactoring related to #281.
No functional changes.
Closes #288. Closes #281.

Move time slice CSV code to `input` submodule

---

.pre-commit-config.yaml
docs/SUMMARY.md
docs/images/dispatch_optimisation.drawio.svg
docs/images/model_overview.drawio.svg
docs/model_diagrams.md

I've had a go at making a couple of diagrams: one which gives an overview of the whole model and one for the dispatch optimisation (I've not done one for the "agent investment" step yet). They both have omissions I know about and also probably some mistakes I don't :upside_down_face:. In any case, hopefully they represent a starting point.
The model overview diagram doesn't currently have the same structure as the `model_description.md` document. There are two reasons for this:
1. I omitted all the carbon budget stuff because I think that's an unnecessary complication at this point
2. I'm assuming that the "base year price discovery" step will just involve running the dispatch optimisation the same way we do for every other year as far as the code is concerned (if not, we can make it a …

Add diagrams for model overview and dispatch optimisation

---

src/agent.rs
src/commands.rs
src/input.rs
src/input/agent.rs
src/input/agent/objective.rs
src/input/asset.rs
src/model.rs
src/simulation.rs

Assets are currently loaded into a single `Model` object along with all the other model data from CSV files. Unlike the rest of the input data though, the pool of assets will change over time. Assets listed in `assets.csv` will be commissioned and decommissioned on set years, but agents can also (de)commission assets during the investment step.
This PR splits the assets out from the rest of the `Model` object. As all the input data is currently loaded in `Model::from_path`, I thought it made sense to make a new function (`input::load_model`) which returns the assets and model separately.
Currently the assets are just stored in a regular `Vec`, but eventually we will probably want to wrap this in a struct so we can have custom methods for updating the pool. For now, I've made a type alias …

Split out assets from `Model` struct

---

src/input.rs

It happened again. When I merged #336 it broke the build because the branch wasn't up to date. Dammit. I've checked the "require branches to be up to date" option for the branch protection rule so this shouldn't happen again.

Fix another build error

---

Cargo.lock
Cargo.toml
src/log.rs

There's an open security advisory about `atty`: https://github.com/EnergySystemsModellingLab/MUSE_2.0/security/dependabot/1
It doesn't actually affect us, but we don't need the `atty` crate anyway, as the functionality is now in the standard library instead. So let's just use that instead.
Fixes #244.

Remove use of `atty` crate

---

src/input/process/flow.rs

Adds a check to make sure no process has multiple flows for the same commodity
Fixes #248

Check for duplicate flows

---

src/input/asset.rs
src/input/process.rs
src/input/process/availability.rs
src/process.rs

In MUSEv2 you can specify the availability of a process over the course of a year as a proportion of maximum capacity. This information is contained in the `process_availabilities.csv` input file.
Currently we read this information into a flat `Vec<ProcessAvailability>`, but it will be difficult to use it in this form. As with the `CommodityCostMap` and `DemandMap`, users can specify ranges of time slices for which a given value applies, so in order to make it easy to look up the values by time slice (as well as verifying that there are no overlapping entries) it makes sense to store it in a map.
The `ProcessAvailabilityMap` ended up being simpler than the others I mention because there's only one "key" value (a `TimeSliceID`). Values can be specified to be lower bounds, upper bounds or …

Store process availabilities in map

---

Cargo.lock
Cargo.toml
src/main.rs

This PR adds the [human-panic](https://crates.io/crates/human-panic) crate to the package and initialises it. This is all that is required to use it with all the default settings.
Note that this does not change the way the input errors are currently displayed because that is useful, immediate feedback to the users. This is for unexpected errors in the code that mean something went wrong and it's not immediately clear what the error in the input file was (unlike with input validation).
It only runs in release mode, so to test it, add in a panic macro somewhere and run the following:
```
cargo run --release run examples/simple
```
You should see this error message:
```
Well, this is embarrassing.
muse2 had a problem and crashed. To help us diagnose the problem you can send us a crash …
```

Install and use the human-panic crate

---

src/commands.rs
tests/example_run.rs
tests/run.rs

Having our integration test built inside the binary (in the `tests` module in `commands.rs`) means that it isn't possible to add more integration tests, because the program will try to initialise twice and fail. For details, see #369.
I've moved our one existing integration test to the `tests` folder and I've added one for the new `example run` command, which wasn't possible before.
Fixes #369.

Fix: Put integration tests in `tests` folder

---

src/agent.rs
src/input/asset.rs
src/input/process/availability.rs
src/process.rs
src/simulation/optimisation.rs

This PR adds the capacity/availability constraints to the optimisation.
The relevant part of the docs is [here](https://energysystemsmodellinglab.github.io/MUSE_2.0/dispatch_optimisation.html#asset-level-capacity-and-availability-constraints). I've deviated from Adam's formulation in a few ways though:
1. We don't need the capacity constraints (at least I don't think so!) because we already calculate the availability for every process for every time slice, so I haven't included this
2. I've moved the denominator of the LHS of the equations to the RHS (so the RHS can just be calculated with a new `Asset::get_capacity_limits()` helper)
3. The limits are inverted (mulitplied by -1 with the start and end swapped) for input flows, as $q<0$ in this case
I think this is correct, but please let …

Add capacity/availability constraints

---

docs/dispatch_optimisation.md
src/commodity.rs
src/simulation/optimisation.rs

This PR computes the cost coefficients for the optimisation using the equation in the dispatch optimisation doc. Although there are only three terms that make up the coefficients, two of them are only applied conditionally (`var_opex` only applies to PACs and `commodity_cost` only applies if a) the user has specified one and b) it's of the right type for the particular commodity flow).
Other changes:
- Fixed up a couple of issues in the dispatch doc
- Changed `CommodityCostMap::get` to take its arguments as references to make the interface cleaner
Closes #299.

Add cost coefficients to optimisation

---

src/simulation.rs
src/simulation/optimisation.rs
src/simulation/update.rs

This escaped my notice before, but commodity prices also vary by commodity, so we need to include a time slice ID as part of the key for the commodity price map.
I came across this while I was working on trying to get prices out of the optimisation result, but you'll also need it for your issue (#378) @TinyMarsh.

Fix: Commodity prices are time-sliced

---

src/log.rs
tests/example_run.rs
tests/run.rs

The current logic we have to disable logging for tests doesn't work for integration tests, which is annoying because it's the only place we need it. So we're now getting a lot of log spam for `cargo test`.
I've fixed it up by setting the `MUSE2_LOG_LEVEL` env var for the two integration tests.

Fix: Disable logging for integration tests

---

src/agent.rs
src/commodity.rs
src/input.rs
src/input/agent.rs
src/input/agent/objective.rs
src/input/asset.rs
src/input/commodity.rs
src/input/process.rs
src/input/process/flow.rs
src/input/region.rs
src/input/time_slice.rs
src/model.rs
src/process.rs
src/region.rs
src/simulation.rs
src/simulation/update.rs
src/time_slice.rs

We make heavy use of `HashMap`s to store data in MUSE2, usually with the key being some kind of user-specified string ID (representing a commodity, process etc.). `HashMap`s are not ordered data structures, meaning if you iterate over their contents you will get a different ordering every time you run the program, even when using the same input files.
While the dispatch optimisation model doesn't care about ordering (even time slices within a year are independent of one another), a consequence of this design is that the output files will be effectively randomly shuffled every time the user runs the program with the same input data, which is annoying and potentially confusing. As it stands, if a user was to e.g. make a bar chart of commodity prices by time slice in Excel, unless they …

Keep (some) input data ordered in MUSE2

---

src/commands.rs

We use the name of the folder the input files are in as a proxy for the model name, specifically when creating the output folder for the model run (e.g. you get something like `muse2_results/my_model_name`). Unfortunately when extracting the bundled example input files, we use a temporary folder, so you get something like `muse2_results/.tmp4eU71Y` instead. Fix by making a subfolder with a proper name in the temp folder.
Fixes #374.

Fix: Don't use temp folder name in output folder path

---

src/commands.rs
src/output.rs
src/simulation.rs

This PR introduces functionality to write commodity prices to a CSV file as part of the simulation output.
* Defined the `CommodityPriceRow` struct and implemented the `write_commodity_prices_to_csv` function to write commodity prices to a CSV file.
* Added a call to `write_commodity_prices_to_csv` within the `run` function to output commodity prices after agent investment.
Fixes #378

Write commodity prices to CSV

---

docs/dispatch_optimisation.md
src/agent.rs
src/commodity.rs
src/process.rs
src/simulation/optimisation.rs
src/time_slice.rs

This PR adds the commodity balance constraints to the optimisation, which ensure supply matches demand for the system.  See detail in docs [here](https://energysystemsmodellinglab.github.io/MUSE_2.0/dispatch_optimisation.html#commodity-balance-constraints).
There are two kinds of commodity that this is relevant for: "supply equals demand" and "service demand". The former is a simple case of just matching supply and demand within the simulation (e.g. coal production has to match the demand from coal power plants etc.). The latter is similar but effectively includes additional demand for outside the system: for example we might need to service a demand for residential heat, so the model effectively needs to produce an excess of the residential heat "commodity" to match this.
This ended up …

Add commodity balance constraints

---

src/input/time_slice.rs
src/process.rs
src/time_slice.rs

This PR adds missing doc comments for time slice- and process-related code. For the time slice code, there's also a small amount of rearranging, but no functional changes are intended anywhere.
Closes #220. Closes #222.

Add missing doc comments for time slices and processes

---

src/commands.rs
src/input.rs
src/input/process.rs
src/main.rs
tests/run.rs

Currently if a fatal error occurs while running the model (e.g. failure to write to file), that message will be written to stderr but not the log file. For more details see issue description: #421 
Fix by using the `error!` macro after the logger is initialised and `eprintln!` in all other cases. I also fixed another small bug where the output folder wasn't being logged properly (we were using the `info!` macro before the logger was initialised, so it wasn't printed anywhere).
I also tidied the CLI handling code a little while I was at it.
Fixes #421.

Fix logging of fatal errors

---

src/simulation/optimisation.rs

It turns out that users can supply a negative commodity cost indicating an incentive, however, the code currently doesn't handle this case correctly. See [discussion here](https://github.com/EnergySystemsModellingLab/MUSE_2.0/pull/410#discussion_r1983102926).
I also noticed that we're not validating commodity cost in any way, so users can currently give a value of `inf` or `NaN`, which doesn't make a lot of sense. I considered adding a check for this, but as it's actually a broader problem (there are lots of input values that we're not checking), I opened a separate issue for it: #426 
Fixes #423.

Fix: Return correct cost coefficient if commodity cost is negative

---

src/simulation/optimisation.rs

This is a temporary hack until we can implement #428 properly, which will require (small) changes to the upstream `highs` crate.
The problem is that Adam wants the objective value for the optimisation (seemingly a scalar value -- I'm honestly not sure of its significance) and there is no way to get that information using the `highs` crate as it stands. You can, however, see this information along with various other stats if you enable logging for the solver. This is a pretty gross hack -- the output is just dumped to `stdout` rather than going through our logger so it won't be written to the log file -- but it should at least allow us to see what this value is in the short term.

Enable logging for HiGHS solver

---

src/agent.rs
src/simulation.rs
src/simulation/investment.rs

Agent investment currently takes place immediately after the dispatch optimisation in the simulation loop. It doesn't really matter as things stand, because it's just a no-op, but I think it will affect things once agents can actually commission/decommission assets. It will also have an effect on the data we write: we want to make sure we attibute things to the correct milestone year.
I *believe* that agent investment should happen at the start of the milestone year, after old assets have been decommissioned, but before new ones have been commissioned (apart from anything, newly commissioned assets will by definition not have been included in the previous run of the dispatch optimisation, so agents won't have information about them yet).
One slightly odd consequence of this is that some …

Reorder simulation loop

---

src/agent.rs
src/simulation/investment.rs

While we don't yet have agent investment, I thought it was still worth adding the relevant method to `AssetPool` to allow us to select/discard assets. I've added some placeholder code to `perform_agent_investment` which uses this method (currently it just retains all assets).

Add scaffold code to select assets based on agent choice

---

examples/simple/agent_objectives.csv
src/agent.rs
src/input.rs
src/input/agent.rs
src/input/agent/objective.rs

This is a nice easy, self-contained change to kick off the plans described in #442 
All I'm doing here is adding a year field to the existing agent_objectives table. The actual work of adding the field is tiny, I just added a `year` attribute to the `AgentObjective` struct, a year column to the csv, and I believe the process of reading in the new data is all automatic.
Most of the work here is to do with validation:
- checking that the year is a valid milestone year
- checking that all agents have at least one objective for each year
I've copied each objective in the table to apply to both 2020 and 2030, but long run we want a better approach (see #444)

Add year field to objectives

---

docs/model_description.md
src/simulation.rs
src/simulation/optimisation.rs
src/simulation/prices.rs

Implements the new commodity price calculation as suggested by @ahawkes in #433 
Main changes to the code:
- created `iter_capacity_duals` to retrieve the dual values for the capacity constraints
- added a check in `add_asset_capacity_constraints` to make sure these constraints are added immediately after the commodity balance constraints
- implemented the new commodity price calculation in `add_from_solution`
I still have a couple of questions:
- should we add capacity constraint duals only for PACs? (I have assumed yes, as I wouldn't think this would apply to side-products such as CO2)
- do we need to do anything different for processes with multiple output commodities? It seems to me that this would have some impact on commodity prices (see [this …

Fix commodity price calculation

---

src/commands.rs
src/commodity.rs
src/input.rs
src/input/agent.rs
src/input/agent/commodity.rs
src/input/agent/region.rs
src/input/agent/search_space.rs
src/input/asset.rs
src/input/commodity.rs
src/input/commodity/cost.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/input/process.rs
src/input/process/availability.rs
src/input/process/flow.rs
src/input/process/parameter.rs
src/input/process/region.rs
src/input/region.rs
src/input/time_slice.rs
src/model.rs

Just a little tidy up of the `input` module. Mostly making things private that don't need to be public, and tidying some import statements. Feel free to tell me if any of this is silly

Spring clean for the inputs module

---

src/agent.rs
src/asset.rs
src/commodity.rs
src/id.rs
src/input.rs
src/input/agent/objective.rs
src/input/agent/region.rs
src/input/agent/search_space.rs
src/input/asset.rs
src/input/commodity/cost.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/input/process.rs
src/input/process/availability.rs
src/input/process/flow.rs
src/input/process/parameter.rs
src/input/process/region.rs
src/input/region.rs
src/lib.rs
src/output.rs
src/process.rs
src/region.rs
src/simulation/optimisation.rs

A few changes to tidy up handling of IDs
- Move id-related code into a new module
- Remove `agent_id` from `AgentSearchSpace`
- Remove `process_id` from `ProcessParameter`
- Remove the `IntoIDMap` trait and method as this was only used once

Refactor ID code

---

src/input.rs

I noticed this while reviewing your PR. It's not actually that big of a deal, but I felt the itch to fix it anyway.

`read_csv_id_file`: Remove unnecessary `contains_key`

---

src/commodity.rs
src/input.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/simulation/optimisation.rs
src/simulation/prices.rs

Removing the `Key` structs, and looking up the respective `HashMaps` with tuple keys using the appropriate ID types

Remove Key structs

---

src/output.rs
src/simulation/optimisation.rs
src/simulation/optimisation/constraints.rs
src/simulation/prices.rs

Small change to the commodity price calculation so that prices are now calculated separately for each region. I _think_ this is correct, but good to get a second pair of eyes. The results for the example model are unchanged (as this model only has one region anyway)
Fixes #431

Calculate commodity prices per region

---

src/input/commodity.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs

Making sure that all SVD commodities have demand data provided, and ensuring that demand is not provided for non-SVD commodities.
I'm mandating that all SVD commodities have demand data for every region, year and time slice. We can maybe revisit this later as a user experience thing if users get frustrated having to add a load of zeros into their files, but I think this is the safest option for now. Will be easier once we've added "all" options for year and region
Fixes #365 
Fixes #366

Extra validation for demand data

---

.devcontainer/devcontainer.json
Dockerfile

I'm currently not able to build MUSE2 on my machine because of #517. I've opened a PR upstream and hopefully that fix will trickle down to us soon. I can probably work around it, but I thought it might be useful to have some container config files to make it easy to get a working toolchain.
The container currently includes all the dependencies needed to build MUSE2 as well as `git` and `mdbook`. I couldn't get `cargo-llvm-cov` or `pre-commit` to work so left those out for now.
In future, it could be handy to add extra Python dependencies for running sample analysis scripts etc. We could also run our CI tests on this image at some point, if we can be bothered.

Add config files to allow developing in a container

---

src/commands.rs
src/main.rs
src/output.rs
tests/example_run.rs
tests/run.rs

Currently files are written to `muse2_results/{model name}`. It would be useful in of itself for users to be able to choose the output directory, but, in addition, adding this extra argument to the `handle_run_command` function allows us to use a temporary dir for tests (#373). It'll also be useful for when we want to write regression tests (#520).
Closes #371. Closes #373.

Allow user to choose output directory

---

src/agent.rs
src/input/agent.rs
src/input/agent/commodity_portion.rs
src/input/agent/objective.rs

As we're only currently supporting the "single" objective type (and likely won't support anything else for the forseeable future) I was able to write this in a more simplified way than planned. I've written a check to disable the other objective types for now.
I'm opening this as draft because this might not be uncontroversial :stuck_out_tongue:. I haven't added commodity IDs as keys to the map yet (#542) because I wanted to run this by you before building on top of it, plus I think it can wait till later anyway.
Instead of a `HashMap<u32, Vec<AgentObjective>>`, I've gone with `HashMap<u32, ObjectiveType>`, as a) we will only have one objective per year and b) that objective won't have any additional parameters. Writing things this way made the validation checks simpler and it should be …

Store agent objectives as a map

---

Dockerfile

@dalonsoa: We've added a devcontainer since you last looked at MUSE 2.0, which may be handy if it turns out your toolchain isn't working for whatever reason. This PR just adds a missing dependency for it.
While the `rust-src` package isn't necessary to build MUSE 2.0, it is useful as it's required by the VS Code Rust extension (for example). Let's just include it.

Dockerfile: Include `rust-src` package

---

src/agent.rs
src/fixture.rs
src/input/agent.rs
src/input/agent/commodity_portion.rs
src/input/agent/objective.rs
src/input/agent/search_space.rs

The agent search space (optionally) constraints which processes an agent can consider for a given combindation of commodity and year. This PR converts the agent search space to be housed in a map rather than a `Vec`, which makes it easier (and faster) to look up partiular entries.
I also changed the `year` field to accept multiple years, as we've done elsewhere, and converted the test code for the agent search space stuff to use `rstest` (so we can have fixtures).
Closes #507.

Convert `AgentSearchSpace` to map

---

docs/user_guide.md

Replaces `env_logger` with `ferm` in the logger documentation. 
Fixes #429

:memo: Use 'ferm' in the log documentation.

---

src/asset.rs
src/simulation.rs

I've added the functionality we need to `AssetPool` to be able to add new assets, by storing assets that have not yet been commissioned separately from those that have. Other than that, I've left the API pretty much the same as it was, except that I've added a new `Asset::commission` method.
Technically issue #486 is about adding new processes to the pool, rather than assets, but we need to work out what the capacity of the newly created asset should be in order to be able to do this. There is [a description](https://energysystemsmodellinglab.github.io/MUSE_2.0/model_description.html#iii-add-new-asset-or-confirm-asset-not-decommissioned) of how to do this in the documentation, but I think it makes sense to deal with that later.
Closes #486.

Allow for adding new assets to pool

---

examples/simple/agent_commodity_portions.csv
examples/simple/agent_cost_limits.csv
examples/simple/agent_objectives.csv
examples/simple/agent_search_space.csv
examples/simple/commodity_costs.csv
examples/simple/process_availabilities.csv
examples/simple/process_flows.csv
examples/simple/process_parameters.csv
src/input/agent/commodity_portion.rs
src/input/agent/cost_limit.rs
src/input/agent/objective.rs
src/input/agent/search_space.rs
src/input/commodity/cost.rs
src/input/process/availability.rs
src/input/process/flow.rs
src/input/process/parameter.rs

This is a really boring PR... Sorry!
We have a bunch of fields called `year` in both the CSV files and the code that can actually take multiple years as an input. Let's rename them to `years` for consistency with other fields (e.g. `regions`).

Rename `year` to `years` for fields that can be multiple years

---

.github/workflows/docs.yml

The CI is currently failing to deploy the docs because the command in the workflow is subtly wrong. The flag is `--markdown-help`, but it's currently `--markdown_help`, which is causing the docs to fail to build. Fix it.

Fix markdown help command in CI

---

examples/simple/commodity_constraints.csv
examples/simple/process_flow_share_constraints.csv
examples/simple/process_investment_constraints.csv

There are three CSV files in the example model that are currently empty and unused anywhere in the code. Support for them will not be added in this milestone (maybe not the engagement). Let's remove them for now.
The rationale for removing them is that a) leaving them in the example model is misleading (changing them won't affect anything) and b) if/when we *do* add support, attempting to run MUSE2 on the old version of the model might not work as the files will be empty (and may have the wrong column headings etc.).
Closes #496.

Remove unused CSV files

---

src/id.rs
src/input/time_slice.rs
src/output.rs
src/time_slice.rs

We have bespoke types for e.g. commodity ID, region ID etc. The two parts of time slices -- seasons and time of day -- are effectively ID types too, so let's enforce this with the type system for type safety and readability. Also implement `Serialize` and `Deserialize` for `TimeSliceID` (composed of a season + time of day) so that we can read/write these values directly without converting to/from strings.

Use ID types for parts of time slice + implement `Serialize`/`Deserialize`

---

src/input.rs
src/input/process/availability.rs
src/input/process/flow.rs
src/model.rs
src/year.rs

We have no guarantees that users won't enter the same year twice or supply years out of order (e.g. "2010;2005"). It would be useful if the code could rely on the years being unique, sorted values, so let's enforce it.
I wrote some tests while I was at it.
Unrelated change: I was looking to see where we were using these parsed years and came across a few unnecessary `clone`s, which I've removed.

`parse_year_str`: Handle out-of-order and duplicate years

---

src/id.rs

We don't want users to name their proceses `all` or whatever as it'll break things, so let's prohibit it. I've currently prohibited empty strings, `all` and `annual` (could cause issues if a user names a season this).
Closes #548.

Disallow certain values for IDs

---

src/agent.rs
src/input/agent.rs
src/input/agent/search_space.rs

While working on #483, I was looking at using the agent search space and realised it's probably easier if we just store the processes (as `Rc<Process>`) in the `AgentSearchSpaceMap` directly, rather than just the process IDs, so I've changed that.

Represent agent search space with `Rc<Process>`

---

src/id.rs
src/simulation/prices.rs
src/time_slice.rs

While working on #595 I noticed that commodity prices were in a random order after we removed the contents of `CommodityPrices::add_from_solution` and were therefore all being added (as `NaN`) in `add_remaining`. The issue is that we're using a `HashSet` to store the IDs of commodities without prices, so, while `CommodityPrices` retains insertion order (being an `IndexMap`), its contents can end up in a random order anyway. We just didn't notice before because we only had one commodity without a price.
There are different ways we could fix this, but I've opted to change `CommodityPrices` to use a `BTreeMap` rather than an `IndexMap`, so the contents are kept ordered according to the commodity ID (i.e. alphabetically). It doesn't particularly matter, but doing it this way means that the …

Fix: Use consistent ordering for commodity prices between runs

---

examples/simple/process_availabilities.csv
src/commodity.rs
src/fixture.rs
src/input/commodity/cost.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/input/process.rs
src/input/process/availability.rs
src/input/time_slice.rs
src/simulation/optimisation.rs
src/time_slice.rs

I've reworked the demand map for commodities to use a `TimeSliceSelection` to represent a time period rather than a `TimeSliceID`, so that we can represent e.g. individual seasons rather than time slices (there will never be a mix in the map though). I've changed the input code to handle this as well as adding some more time slice-related functionality (e.g. `TimeSliceSelection::iter_at_level` for iterating over time slice selections at the specified time slice level).
This is a pretty big set of changes, but I figured it made sense to do this before we add the demand satisfaction constraint (#578).
While I was busy changing the time slice-related code, I disallowed the option to represent a `TimeSliceSelection::Annual` as an empty string in input files, as I think it's a bit of a …

Allow user to specify demand at level of season or whole year

---

src/asset.rs
src/output.rs
src/simulation.rs
src/simulation/investment.rs
src/simulation/optimisation.rs
src/simulation/optimisation/constraints.rs

I've reworked the `AssetPool` API as suggested in #591 to store assets as reference counted values. This has a couple of advantages over the current approach, namely:
1. We can store a representation of assets as (part of) the keys for the `VariableMap` as well as in the constraints keys data structures, which means we don't have to pass around the `AssetPool` all over the place
2. When we come to writing the dispatch code, we can store both retained assets and new assets to be commissioned in the same `Vec` (or whatever)
I've started on 1 by updating the existing data structures and functions. I made a small wrapper (`AssetRef`) around `Rc<Asset>` to be used for keys in maps etc. so that we can have custom `Eq` and `Hash` methods (just using the ID, otherwise performance would be crap). …

Store assets as reference counted values and rework `AssetPool` API

---

Cargo.lock

The current version of `highs-sys` specified in `Cargo.lock` doesn't compile on gcc v15, but a new version with a fix has been released. As it's an indirect dependency (unlike the main `highs` crate), it won't be updated by dependabot, so we need to update it manually. I've done this by running `cargo update`.
Fixes #517.

Fix build on gcc v15 by updating `highs-sys` dependency

---

Cargo.lock
Cargo.toml
build.rs
src/input.rs
src/model.rs
src/output.rs
src/output/metadata.rs
src/simulation.rs

It makes sense to include some metadata in the output folder along with the actual data. This is partly to help users figure out which model runs different sets of output files correspond to, but we can also include information about the version of MUSE they're running and their system for the sake of debugging/reproducibility.
There could be more information provided in the `[run]` section, but I figure this is a good place to start. Suggestions about what to include/exclude etc. are welcome!
I used two external crates to get information about the program build (`built`) and the running system (`platform-info`).
This is an example of the metadata file I get on my system:
```toml
[run]
model_path = "/tmp/.tmp5UUvxn/simple"
datetime = "Tue, 10 Jun 2025 14:07:13 +0100"
[program]
name = …
```

Write metadata to TOML file in output folder

---

src/asset.rs
src/output.rs

Using the asset's ID in the output files, rather than displaying the full asset details every time. For now, I'm keeping asset ID's as integers. We could think about making these more descriptive in the future, as outlined in the issue (perhaps worth opening up another issue for this).
In theory, users could get back what they had before by doing a join between the table of interest (e.g. commodity_flows) and the assets table.
One other thing I noticed is that the assets table is creating a row for each asset every milestone year that the asset is active. I guess in most cases the user could then figure out the decommission year based on the last entry for the asset, but I think it would be cleaner to have a decommission year column, which will be modified as the simulation progresses, …

Use `AssetID` in output files

---

.github/actions/codecov/action.yml
.github/workflows/cargo-build-and-test.yml
.github/workflows/cargo-test.yml

I've been fiddling with our CI workflow for running tests while working on #616 and realised it could be simplified a bit. Previously, the Ubuntu runner was also checking documentation and uploading test coverage in addition to running the actual tests, but now the only extra thing it's doing is uploading coverage, so it's simpler if we just have one "job" that covers all the runners.
I also made various other small tweaks, including changing the name of the workflow (so we'll need to update our branch protection rules).

Tidy CI workflow

---

src/asset.rs

Users can update the asset pool by calling `replace_active_pool`. The problem is that the active pool of assets must be sorted by ID internally and we have no idea what the ordering of the assets provided will be and don't check. Fix by sorting the pool after replacing.

Fix: Sort assets by ID after replacing pool

---

.github/workflows/cargo-test.yml
.github/workflows/check-docs.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
assets/readme/README.md
assets/readme/readme_linux.txt
assets/readme/readme_macos_arm.txt
assets/readme/readme_windows.txt

This PR adds a CI workflow to build and upload executable files on release. The executables are stored in an archive with a readme file and a copy of the licence. Maybe we'll want a changelog in there too at some point.
In theory the program should run without any extra dependencies being installed.
I've also set the workflow to run when we push to `main`. I know that's a little odd, but I'd like to check that things are still building as we go along, as they could stop working when we update dependencies etc. (e.g. the old version of `g++` we're using might not be compatible with a newer version of HiGHS). In this case, the executables are uploaded as test artifacts.
Unrelated change: I noticed we were missing the `workflow_dispatch` trigger for most of our workflows, so I've added it. …

Upload binaries on release

---

src/asset.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/input/process.rs
src/output.rs
src/process.rs
src/simulation/optimisation.rs
src/simulation/optimisation/constraints.rs
src/time_slice.rs

As before, these two kinds of constraint are pretty similar, so I took the approach we had previously and just added one function to handle both of them. We will also want to use the duals of these values in the result for calculating prices (as we did before), so it makes sense to lump them together.
Closes #578. Closes #577.

Add commodity balance and demand satisfaction constraints

---

src/simulation.rs
src/simulation/prices.rs

This PR re-adds the code for calculating commodity prices using broadly the same method as before, i.e. the commodity balance duals plus the highest capacity duals. Given that we no longer have PACs, we now just consider all the output flows for each asset.
@ahawkes says this should be fine, but that we should check, so I'll open this as a draft and give him a chance to look at the new numbers before we merge. Is that ok, Adam? I've attached the results below. An alternative would be to just merge it now (so that we at least have some prices to work with) and revisit it later. Up to you.
[muse2_results_20250618_b0b26db2.zip](https://github.com/user-attachments/files/20791663/muse2_results_20250618_b0b26db2.zip)
Closes #589.

Calculate commodity prices using dual values

---

Cargo.lock
Cargo.toml
src/lib.rs
src/metrics.rs
src/units.rs

*Please include a summary of the change and which issue is fixed (if any). Please also
include relevant motivation and context. List any dependencies that are required for
this change.*
Fixes #171

LCOX calculation with strict enforcement of units

---

src/units.rs

I was fiddling with unit types on another branch and noticed a couple of small problems:
1. A unit type `U` divided by `U` should yield `Dimensionless`, not `U`
2. We should pass self by ref (`&self`) not value (`self`) for various methods of unit types, otherwise it'll be consumed when they're run

A couple of small fixes for unit types

---

src/commodity.rs
src/input/commodity/demand.rs
src/input/commodity/levy.rs
src/input/process.rs
src/input/process/flow.rs
src/output.rs
src/process.rs
src/simulation/optimisation.rs
src/simulation/prices.rs
src/units.rs

This PR includes two changes:
1. Rename "energy" types to "flow" types, as @ahawkes suggested
2. Remove the option to multiply unit types by things of the same type, as discussed
I decided not to include the `UnitType` trait stuff from #656 as it's not currently needed anywhere. We can cherry-pick it later, if needed.

More tweaks to unit code

---

src/input/process.rs
src/input/process/flow.rs
src/process.rs
src/simulation/prices.rs

This is only a small change, but because it touches code in various places I thought it should be a separate PR.
I've added `is_input` and `is_output` helper methods to `ProcessFlow`, partly because it's now quite verbose to check whether something's an input/output flow (`flow.coeff > FlowPerActivity(0.0)`) but also because I think it would be easy to miss that someone had put a `>` instead of a `<`. I think it's better to be explicit.

`ProcessFlow`: Add `is_input` and `is_output` helper methods

---

src/asset.rs
src/output.rs
src/simulation.rs
src/simulation/optimisation.rs
src/simulation/optimisation/constraints.rs
src/time_slice.rs

I've added the bare minimum of functionality to allow for optionally including candidate assets in the dispatch optimisation, as well as the active pool. In practice, we will only want to do this on the final iteration of the investment step and the rest of the time, only the active assets will be included. There are two reasons for wanting to do this: 1) to get prices for commodities not produced in the last milestone year and 2) to calculate reduced costs for candidate assets (given by the column duals). I've added an `iter_reduced_costs_for_candidates` method to `Solution`, but it's not currently used anywhere.
Note that the constraints are applied to both active and candidate assets. Individual commodity balance constraints can include a mix of active and candidate assets (this is …

Allow candidate assets in dispatch

---

src/agent.rs
src/asset.rs
src/fixture.rs
src/input/agent.rs
src/input/agent/commodity_portion.rs
src/input/agent/search_space.rs
src/input/asset.rs
src/input/commodity.rs
src/input/commodity/demand.rs
src/input/commodity/demand_slicing.rs
src/input/commodity/levy.rs
src/input/process.rs
src/input/process/parameter.rs
src/process.rs
src/region.rs

This is possibly the most boring PR on the planet, but it involves little changes all over the place so didn't want to include it with something else.
I've changed everywhere that we store `RegionID`s in a `HashSet` to use an `IndexSet` instead. The reason is because I want to iterate over the regions a process can operate in with a deterministic order. The problem is that to do this we'd need to change things in various other places (e.g. `parse_region_str`) so I figured it would be easier to do in one go.

Represent collections of `RegionID`s with `IndexSet`s, not `HashSet`s

---

src/model.rs
src/simulation/investment.rs

I've got other bits of agent investment code that are on hold while we figure out #689, but I figure this is worth merging now, even if it's small.
This PR adds code to calculate the demand profile for commodities of interest. For now, this will just be the SVD commodities, but I've tried to write it in such a way that it'll be useful for subsequent rounds of agent investment looking at SED commodities.
Unrelated change: Fixed a doc comment re the pricing strategy.
Closes #645.

Get demand profile for SVD commodities

---

src/input/agent.rs
src/input/agent/search_space.rs

As we discussed, for missing entries in `agent_search_space.csv`, we should assume that agents are able to choose any process whose primary output is the commodity for which the agent is responsible.
I took your suggestion of filling missing entries in advance when we load the input data, rather than waiting until we need that info, as it seemed the cleanest way to do it.
Because the input format is a bit odd and technically currently allows users to have different primary outputs in different regions, we include any process which has the commodity as a primary output in at least one region for the given year. This is a bit weird, but will probably do until we do #666.

Fill agent search spaces for missing commodities/milestone years

---

src/asset.rs
src/simulation/optimisation.rs

A couple of small fixes:
1. `AssetRef`s shouldn't compare agent IDs for non-commissioned assets, as we want to match regardless of this field (e.g. getting reduced costs for a candidate asset)
2. The `Solution` object was returning the wrong variable keys for `iter_reduced_costs_for_candidates()`
I also added a terser implementation of `Debug` for `Asset` as the default one was a bit too verbose (e.g. it included all the fields of the `process`) and it made debugging hard.

Small fixes for optimisation/investment

---

src/simulation/investment.rs

As discussed, here are the changes to make it easier to include your work on computing the commodities of interest.
There were two things that I noticed needed changing (but I might have missed something):
1. Change `get_demand_profile` to produce a demand profile for all commodities, not just the current COIs
2. Reorder the investment loop to iterate over regions before agents, which is closer to how things will be done once we have #650 
The way `get_demand_profile` currently works is to sum all positive flows for a given commodity, as supply==demand for both SVD and SED commodities (albeit for SVDs the demand is external), which will have odd consequences for commodities of type "other". That said, I don't think we care about OTH commodities for investment... right? I'm assuming it …

Refactor investment code to allow for supplying commodities of interest

---

Cargo.lock
Cargo.toml
src/output.rs
src/simulation/optimisation.rs
tests/data/simple/debug_solver.csv
tests/data/simple_mc/debug_solver.csv

@ahawkes mentioned that it's useful to be able to see the objective value for a dispatch optimisation. Up until the latest release of the `highs` crate though, it was not possible to get the objective value from the solution, so we had a nasty hack where we enabled the HiGHS logger to dump many things, including the objective value, to the console. This is output not saved into the program log file and will only get harder to read as we add more dispatch optimisations per milestone year (#651).
I made an upstream PR and now we can get the objective value from the HiGHS solver. So I've turned off the logger and now write this value to an output file instead.
We could also potentially use the objective value to calculate profitability index/LCOX more quickly or cleanly, but that's for …

Write objective values for dispatch optimisation to file

---

src/simulation/investment/appraisal/optimisation.rs
src/simulation/optimisation.rs

In both the places in the code where we run a HiGHS model, we're not handling errors properly. I assumed the `try_solve` method would return an error if the status was not optimal, but actually it only does so if the model is "not coherent". (I wasn't able to make a model that seemed to trigger this error, but let's assume that it can happen.) This makes sense because you might want to do something with the result of an LP problem even if the result is non-optimal.
Fix by adding a helper function -- `solve_optimal` -- which includes the proper check. I've stuck it in `src/simulation/optimisation.rs`, which may not be the best place for it, but other suggestions are welcome!

Fix: Need to check optimisation status is optimal

---

src/model.rs

I've added a couple of macros for defining the helper functions for getting model parameters' default values, because it seemed cleaner: one for unit types and one for regular numbers.
There weren't any params defined for regular numbers, so I added one that we need for #653.

Add helper macros for default param values

---

src/asset.rs
src/fixture.rs
src/input/asset.rs
src/simulation.rs
src/simulation/investment.rs

This creates an `AssetState` enum which captures the state of the asset as it gets commissioned and decommissioned. All the fields that were once optional (`id`, `agent_id`, `decommission_year`) are now held in this enum within the appropriate states.
There are two pathways that an asset can follow in its life cycle:
`Future` -> `Commissioned` -> `Decommissioned`
`Candidate` -> `Commissioned` -> `Decommissioned`
The first pathway is for assets defined in the input data. The second pathway is for assets selected by the investment algorithm, which also determines the level of capacity.
The methods performing these transitions (`commission_future`, `commission_candidate` and `decommission`) have checks in place to ensure that they are only called on assets of the appropriate state
I've also …

Create `AssetState` enum

---

schemas/input/commodity_levies.yaml
src/input/commodity/levy.rs
src/process.rs
src/simulation/prices.rs

This PR aims to fix two issues that might appear in reasonable scenarios
1. Not having any levies at all.
2. Having levies for a commodity in a region but not in other regions.
At the moment, in these two scenarios things fail because of the problem described in [this comment](https://github.com/EnergySystemsModellingLab/MUSE_2.0/pull/778#issuecomment-3224294389). 
The approach has been to:
1. Allow having an empty levies file; and
2. Populate the levies with zeros in all the missing cases. This is done after validating the levies provided, if any, so they are complete - the have been provided for all years and timeslices, but not regions.
This approach might be overkilling in the sense that, most likely, this is going to be a huge vector of zeros, but it seems like the simplest approach …

Fix levies so there's no error if they are missing

---

src/output.rs
src/simulation/investment.rs

I've noticed that every time you run `tests/regenerate_all_data.sh`, the various `debug_appraisal_results.csv` files seem to change. The changes are all caused by small rounding errors in the appraisal results. They occur at random, so if you commit these changes then rerun the script, the files will change again.
This doesn't matter much, because the changes are all smaller than the tolerance we've specified, so tests will still pass. But it does mean that every time someone updates the regression test data, the `debug_appraisal_results.csv` files will also get changed for no particular reason, which is unnecessary churn.
The issue is ultimately caused by the fact that the maps representing demand are iterated over in a non-determinstic order because they are `HashMap`s. This can easily …

Fix non-deterministic rounding of appraisal results

---

schemas/input/agent_objectives.yaml
src/input/agent/objective.rs

We've flipflopped on this a bit, but for a time we were planning to use NPV rather than LCOX for the example models, as we thought that there were problems with the LCOX implementation. I updated the docs and changed the code to issue a warning if the user chose the LCOX option. As it happened, it turned out that the LCOX implementation was basically fine and using NPV sometimes caused problems (e.g. a fatal error if used with the `simple` example: #716), so we switched the examples back to LCOX instead. There was some discussion about fixing NPV and reverting this change (#718) but we decided against it (at least in the short term).
This PR changes the documentation and the in-program warning about LCOX to warn about NPV instead, so that it's clear to users what they "should" be doing. …

Warn about use of NPV rather than LCOX

---

.github/actions/generate-docs/action.yml
.github/workflows/cargo-test.yml
.github/workflows/crates-io.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/update-rust-toolchain.yml
Dockerfile
rust-toolchain.toml

It seems that you can pin a specific version of the Rust toolchain that you want to use (in a `rust-toolchain.toml`) and `rustup` will respect it. When you run `cargo` it'll download the requested toolchain if it's not installed and use that for building/linting/etc. your project. Kinda neat.
I think this would be useful for us for a few reasons:
- Sometimes new `clippy` warnings are introduced when the CI runner's toolchain is updated and so CI starts failing
- Developers may see confusing build failures if their toolchain is older than the latest `stable` one being used by the project
I've pinned it to the latest stable toolchain (v1.89.0) for now and I've added a GitHub workflow which purports to be able to automatically bump this when a new version is released. Let's see how well it …

Pin Rust toolchain version

---

src/cli.rs
src/cli/example.rs
tests/regression.rs
tests/run.rs

If the `debug_model` setting is set to `true` in the user's `settings.toml` file, then the regression tests will fail. The tests should not depend on user settings. Fix by changing a couple of functions to accept an optional `Settings` struct, to allow tests to provide their own settings.
It's a little ugly, but I couldn't think of a nicer way to do it.
Fixes #814.

Don't load `settings.toml` in tests

---

src/commodity.rs
src/finance.rs
src/input/commodity/demand.rs
src/simulation/investment/appraisal/constraints.rs
src/time_slice.rs

This is just a small cleanup. It turns out you can use square brackets to get items from a map rather than having to use the `get` method, which makes things a bit cleaner, so I've done a find and replace.

Replace `get` + `unwrap` with square brackets where possible

---

src/input.rs
src/input/commodity/demand.rs
src/input/process/availability.rs
src/input/process/parameter.rs

Some of the error messages displaying missing keys could end up being extremely long if there's lots of missing data, so I've introduced a cap of 10 items to prevent messages getting too long. If there are more than 10 missing items it will print the first 10, followed by "...and x more"
I haven't made the cap configurable as it seems a bit niche to want to change this, but can do if you think it would be useful
Hopefully this is all the places where this could be a problem (I didn't look through every single error message in the code, just did a search for "missing_keys")
Fixes #852

Cap error messages

---

src/input.rs
src/model.rs
src/model/parameters.rs

There are currently some missing validation checks for some model parameters. This PR adds the missing checks.
While I was at it, I reorganised the model params code, by renaming some things and moving the model parameter-specific code into a new `model::parameters` submodule.
Fixes #853.

Tidy model params code and add missing validation checks

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
assets/settings.toml
src/cli.rs
src/log.rs
src/settings.rs

We provide a placeholder `settings.toml` that's bundled with releases with default options commented out, but it's easy to forget to update this file, so it would be better to just generate it instead, which is what I've done in this PR.
I've done this by adding a `dump-default-settings` command to `muse2`, which is then used to generate the placeholder file (though it could also be used by users to see what the default options are).
This is partly in preparation for #255, which should make configuring `muse2` easier. The current approach of having a `settings.toml` file that must be in the CWD is a bit of a hack.

Add command to generate placeholder `settings.toml` file

---

src/settings.rs

Looks like I broke things in my last PR (#857). Oops.
Now, if you run `muse2` and **don't** have a `settings.toml` file, you'll see an error like this:
```
Error: Failed to initialise logging.
Caused by:
Unknown log level:
```
The problem is that `Settings::log_level` is set to an empty string by default when you call `Settings::default()`, which is what's used if there is no settings file.
The solution is to apply the `#[serde(default)]` attribute to the whole `Settings` struct, rather than individual fields, and implement the `Default` trait manually for it.
This is actually pretty clean and would maybe be a nicer way of setting default values of params for `ModelParameters` too, rather than all that macro business.

Fix: Program fails to run if no `settings.toml` file present

---

src/asset.rs

If an asset defined in the `assets.csv` input file has a decommission year (== commission year + lifetime) less than or equal to the first milestone year, then it will be commissioned in the first milestone year and included in the simulation for that year before being decommissioned in the second milestone year. This is a bug.
Easy to fix: we just need another check in `AssetPool::commission_new` to ignore future assets which have already been decommissioned.
Fixes #862.

Fix: Don't commission already-decommissioned assets from input file

---

Cargo.lock
Cargo.toml
docs/user_guide.md
src/cli.rs
src/cli/settings.rs
src/lib.rs
src/settings.rs

This has been bugging me for a while, so I've had a go at it, even though it's low priority.
Currently the program settings are loaded from a `settings.toml` file in the CWD, if one exists, but this isn't ideal -- users should be able to change directory without the program settings changing!
There are standard places to store program config files (differing between OSes), so we should use this as a place to store the settings file instead. However, in doing this, it may make it harder for users to figure out where they should be creating their settings file etc., so I think it makes sense to add some helper commands to make this easier.
I've added a `settings edit` command, which allows users to edit the program settings. If the settings file doesn't exist, a placeholder file with the …

Move settings file to app config folder and add commands to modify

---

.github/workflows/auto-merge.yml

We use a variation on this workflow in lots of repos to automatically merge bot PRs (from dependabot and pre-commit), to make it easier to stay on top of these version bumps. I figure it's probably safe to add it to this repo too. We've got a pretty good test suite and I haven't noticed any breakage caused by bumping any package versions in the last year, so it's probably fine. I also added @rse-ci-imperial to the list of bots, so that bumps to the Rust toolchain version also get auto-merged.
I think we should remove this between engagements, but we'll be working on MUSE2 for a few months yet.

Add CI workflow to auto-merge bot PRs

---

src/asset.rs
src/output.rs
src/simulation.rs
src/simulation/investment.rs

As part of the series of fixes for reduced costs (#876), we will soon be transitioning to using the same method for calculating reduced costs as we currently do for existing costs (#879). This means that candidate assets will need to be associated with a particular agent, as the reduced cost calculation will vary depending on the agent's objective (see my other PR: #882). Currently, candidate assets are agent-less unless and until they are selected by an agent, at which point their `state` is changed to `AssetState::Selected` and they are assigned an agent ID. All other asset types already have an associated agent ID; this PR just changes things so candidates have one too, by making `agent_id` a field of `Asset` rather than a value embedded in different `AssetState` variants.
This means …

Give candidate assets an agent ID
