- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
These templates are based on the ones we have for MUSE v1.
Closes #12.
> Add templates for GitHub issues and PRs

- Cargo.toml
- src/muse2.rs
This PR adds some basic code showing how to use the `good_lp` crate to solve a problem. I based my implementation on the example code given for the crate, but use the HIGHS solver for the problem. NB: The `highs` crate needs a C++ compiler to be installed when building it.
`good_lp` provides many solver backends that can be used instead, see: https://github.com/rust-or/good_lp?tab=readme-ov-file#solvers
@ahawkes I hope you don't mind my tagging you as a reviewer, but I just wanted to check that this is the sort of thing you were looking for.
Closes #2. Closes #3.
> Add example LP code

- .github/workflows/cargo-build-and-test.yml
Fix tarpaulin linking error by explicilty linking against zlib. Also add some missing dependencies to the container.
I don't know why these hacks are needed, but it is working now!
> Attempt to fix codecov

- README.md
> Add a few badges to the README

- .vscode/launch.json
Change args to point at settings.toml
Fixes #75 
- [x ] Bug fix (non-breaking change to fix an issue)
> change args to point to the settings.toml

- src/process.rs
It is actually permitted for process parameters to include start and end years outside the range of milestone years, even though we don't allow it. Remove the check.
In addition, add a new check that `start_year <= end_year`.
Fixes #135.
> process.rs: Fix check for `start_year` and `end_year`

- src/input.rs
This PR replaces the standard Result type with the anyhow result type in the input.rs module
Fixes #195
> Use `anyhow::Result` for input.rs

- .markdownlint.yaml
- docs/SUMMARY.md
- docs/introduction.md
- docs/model_description.md
I've taken sections 1, 2 and 4 from the original document to create a model description page in the documentation.
The original conversion was done  with pandoc, and I've done some tweaking to improve layout/formatting, but the content is pretty much the same
Fixes #159
> Add model description to documentation

- src/agent.rs
- src/commodity.rs
- src/process.rs
Adding some doc strings based on the inputs in the SRS documentation. 
Fixes   (issue) #212
> adding code documentation

- src/region.rs
- src/time_slice.rs
Continuation of my previous PR of adding the in code documentation for the region and time_slice files. 
Fixes #162  (issue)
> adding docs for the region and time_slice structs

- src/agent.rs
Minimal changes required to adapt `agent.rs` to use `anyhow` for error handling.
Fixes #250
> Apply anyhow to agent.rs

- src/agent.rs
- src/commodity.rs
- src/input.rs
- src/process.rs
- src/region.rs
I've been working on #281 and decided it probably made sense to make a separate PR for any changes to the code that aren't simply moving bits around, so that they don't get lost in the big diff.
This includes spelling fixes, adding doc comments etc.
Closes #218. Closes #221.
> Misc changes before refactor

- README.md
- docs/SUMMARY.md
- docs/dispatch_optimisation.md
- docs/glossary.md
- docs/introduction.md
- docs/model_description.md
I've made various small tweaks to the docs.
Commit summary:
* Reorder docs chapters so that details of the model are together and developer guide is at the end
* Use a better link for documentation in readme
* Tweaks to "model description" document (including changing a few US spellings)
> Docs tweaks

- .gitignore
I was using venv to install pre-commit and this was annoying me. Worth implementing?
> Add virtual environment directories to `.gitignore`

- docs/developer_guide.md
- docs/dispatch_optimisation.md
- docs/glossary.md
- src/commodity.rs
I've made some changes to the docs following an email exchange with @ahawkes:
* The command to run the example in the docs was wrong so I've updated it
* I've added instructions on how to update your Rust toolchain
* I've added some detail to the glossary after @ahawkes clarified some things for me (and a couple of doc comments too)
* Added fuller descriptions of some variables to `dispatch_optimisation.md`
> More docs tweaks

- docs/dispatch_optimisation.md
- docs/glossary.md
- docs/model_description.md
Some document updates as discussed with @alexdewar 
- [x ] Documentation (improve or add documentation)
- [x ] All tests pass: `$ cargo test`
- [x ] The documentation builds and looks OK: `$ cargo doc`
> Doc updates

- .gitignore
- docs/images/model_overview.drawio.svg
- src/agent.rs
- src/input/process/availability.rs
- src/simulation.rs
- src/simulation/optimisation.rs
- src/simulation/prices.rs
- src/simulation/update.rs
This PR is basically just a bit of fairly high-level spring cleaning for the optimisation. I waited to do these various bits and pieces until after we'd merged all the other PRs so we didn't get merge conflicts.
The biggest change is that I moved all of the commodity price-related code into a separate `prices.rs` file. I also made the functions for updating prices into methods of the `CommodityPrices` struct, which I think is a bit tidier. I've dropped the `update_commodity_flows` function because we don't need it (I don't think we'll actually need to store the flows anywhere, just iterate over them), so there was nothing left in `update.rs` and I deleted it.
Besides that, there are a bunch of other misc things:
- Remove superfluous logging statements
- Return errors from …
> Tidy-up of dispatch optimisation code

- docs/developer_guide.md
Adds a section to the developer guide about installing C++ tools for HiGHS. @alexdewar feel free to modify or add details as you understand all this stuff better than me
> Link documentation for building highs

- src/asset.rs
- src/fixture.rs
- src/input/process.rs
- src/input/process/availability.rs
- src/input/process/flow.rs
- src/input/process/parameter.rs
- src/process.rs
- src/simulation/optimisation.rs
- src/simulation/optimisation/constraints.rs
Storing a vec of years over which the process operates, rather than a range
Fixes #541
> Store vec of years in `Process`

- src/id.rs
- src/input/agent/commodity_portion.rs
- src/input/agent/cost_limit.rs
- src/input/agent/search_space.rs
- src/input/asset.rs
- src/input/commodity/cost.rs
- src/input/commodity/demand.rs
- src/input/commodity/demand_slicing.rs
- src/input/process/availability.rs
- src/input/process/flow.rs
- src/input/process/parameter.rs
- src/region.rs
- src/time_slice.rs
I've made various small tweaks to the ID code here:
- Amalgamate the `get_id` and `get_id_by_str` functions by using a type parameter
- Change `get_id` to return ID by reference
- Implement `IDCollection` for `IndexMap`s so we can use the `get_id` method on those too
> Various tweaks to ID code

- src/process.rs
- src/simulation/optimisation.rs
Implement the code for calculating the cost coefficients for the optimisation for the new model. I *think* I've calculated these correctly, but let me know if there's something I've missed.
There should probably also be tests, but I'll wait to confirm there's nothing else to do before writing them.
Closes #590.
> Add cost coefficient code

- src/output.rs
- src/simulation/optimisation.rs
- src/simulation/optimisation/constraints.rs
- src/simulation/prices.rs
This is much simpler than it was when we had to consider PACs.
Closes #579.
> Add capacity constraints

- src/input/process/flow.rs
It seems I managed to confuse myself with the convoluted code for getting/inferring the primary output for process flows in the input layer.
If the primary output for a set of process flows is specified explicitly (i.e. by putting `true` in the `is_primary_output` column), rather than inferred (which we can do if there is only one output flow) then the `is_primary_output` field is still left as `false` for that output flow, which is not correct. Fix this.
> Fix: Primary output should be updated if specified explicitly too

- docs/file_formats/generate_docs.py
- docs/file_formats/templates/output_files.md.jinja
- schemas/output/assets.yaml
- schemas/output/commodity_flows.yaml
- schemas/output/commodity_prices.yaml
This PR adds schemas to document the main CSV output files produced by MUSE2. I've decided against documenting the debug ones for now.
I think most of the files are pretty self-explanatory, but it's good to have a reference for these things, especially as it will inevitably become more complicated with time.
Closes #529.
> Document format of output files

- src/graph.rs
I was just looking at the graph code and realised the validation we do for the different time slice levels could be combined into a single loop. It's probably just a matter of taste, but I think it's a bit tidier this way.
> `graph.rs`: Combine validation steps for different time slice levels
